name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Hello world
      id: hello-world
      uses: education/autograding-io-grader@v1
      with:
        test-name: Hello world
        setup-command: ''
        command: bash solution/hello.sh
        input: ''
        expected-output: Hello World!
        comparison-method: exact
        timeout: 1
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        HELLO-WORLD_RESULTS: "${{steps.hello-world.outputs.result}}"
      with:
        runners: hello-world
